# autogenerated by txs
\colorpro#S
FOGRA39L_coated.icc#S
\__file_name=FOGRA39L_coated.icc#S
\__file_name=colorprofiles.tex#S
\__file_name=sRGB.icc#S
\__file_seen_FOGRA39L_coated.icc:#S
\__file_seen_colorprofiles.tex:#S
\__file_seen_sRGB.icc:#S
__file_name=FOGRA39L_coated.icc#S
__file_name=colorprofiles.tex#S
__file_name=sRGB.icc#S
__file_seen_FOGRA39L_coated.icc:#S
__file_seen_colorprofiles.tex:#S
__file_seen_sRGB.icc:#S
colorprofiles.tex#S
csnameendcsname#S
sRGB.icc#S
